# ClimateGuard AI - Feature Reduction

This notebook removes duplicate unit-conversion columns from the cleaned weather dataset before feature engineering.

Input: `../data/processed/02_cleaned_data.csv`
Output: `../data/processed/03_feature_reduced_data.csv`

## 1. Import Libraries

In [4]:
from pathlib import Path

import pandas as pd

## 2. Load Cleaned Data

In [5]:
input_path = Path('../data/processed/02_cleaned_data.csv')
df = pd.read_csv(input_path)

print(f'Loaded data from {input_path}')
print(f'Initial shape: {df.shape}')
display(df.head())

Loaded data from ..\data\processed\02_cleaned_data.csv
Initial shape: (119398, 42)

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,29-08-23 10:45,27.5,81.5,...,12.6,18.5,1,2,5:59 AM,6:41 PM,5:42 PM,3:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,29-08-23 10:45,27.5,81.5,...,10.7,14.2,1,1,6:00 AM,6:40 PM,5:39 PM,3:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,29-08-23 10:45,26.3,79.3,...,16.8,20.7,2,2,5:56 AM,6:34 PM,5:32 PM,3:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,29-08-23 10:45,25.6,78.1,...,4.9,6.6,1,1,6:00 AM,6:38 PM,5:36 PM,3:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,29-08-23 10:45,27.2,81.0,...,11.4,14.8,1,1,6:01 AM,6:39 PM,5:38 PM,3:42 AM,Waxing Gibbous,93

## 3. Remove Duplicate Unit Columns

In [6]:
columns_to_remove = [
    'temperature_fahrenheit',
    'wind_mph',
    'pressure_in',
    'precip_in',
    'feels_like_fahrenheit',
    'visibility_miles',
    'gust_mph',
]

missing_columns = [column for column in columns_to_remove if column not in df.columns]
if missing_columns:
    raise ValueError(f'Required columns not found: {missing_columns}')

reduced_df = df.drop(columns=columns_to_remove)

assert not set(columns_to_remove).intersection(reduced_df.columns)
print(f'Removed columns: {columns_to_remove}')
print(f'Reduced shape: {reduced_df.shape}')
display(reduced_df.head())

# Save the reduced dataset
output_path = '../data/processed/03_feature_reduced_data.csv'
reduced_df.to_csv(output_path, index=False)

print(f"\nReduced dataset saved to: {output_path}")

Removed columns: ['temperature_fahrenheit', 'wind_mph', 'pressure_in', 'precip_in', 'feels_like_fahrenheit', 'visibility_miles', 'gust_mph']
Reduced shape: (119398, 35)

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,29-08-23 10:45,27.5,Partly cloudy,...,12.6,18.5,1,2,5:59 AM,6:41 PM,5:42 PM,3:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,29-08-23 10:45,27.5,Sunny,...,10.7,14.2,1,1,6:00 AM,6:40 PM,5:39 PM,3:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,29-08-23 10:45,26.3,Partly cloudy,...,16.8,20.7,2,2,5:56 AM,6:34 PM,5:32 PM,3:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,29-08-23 10:45,25.6,Cloudy,...,4.9,6.6,1,1,6:00 AM,6:38 PM,5:36 PM,3:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,29-08-23 10:45,27.2,Cloudy,...,11.4,14.8,1,1,6:01 AM,6:39 PM,5:38 PM,3:42 AM,Waxing Gibbous,93

Reduced dataset saved to: ../data/processed/03_feature_reduced_data.csv

## Next Step

Use `03_feature_reduced_data.csv` as the input for `03_feature_engineering.ipynb`.